import type { LPMName } from "../lpmRegistry";

/**
 * Sandbox test buyer country codes per LPM, used only in tests. Kept out of
 * `LPM_REGISTRY` so this fixture data isn't bundled into the shipped package.
 */
export const TEST_BUYER_COUNTRY: Record<LPMName, string> = {
  ideal: "NL",
  bancontact: "BE",
  eps: "AT",
  blik: "PL",
  mybank: "IT",
  trustly: "SE",
  p24: "PL",
  multibanco: "PT",
  bizum: "ES",
  swish: "SE",
  twint: "CH",
  wechatpay: "CN",
  verkkopankki: "FI",
  payu: "PL",
  mbway: "PT",
  satispay: "IT",
  wero: "DE",
  floa: "FR",
  grabpay: "SG",
  pixInternational: "BR",
  sepa: "DE",
  doku: "ID",
  estonia: "EE",
  gopay: "ID",
  alipay: "CN",
  indonesiaBanks: "ID",
  kredivo: "ID",
  linkaja: "ID",
  ovo: "ID",
  paysera: "LT",
  skrill: "DE",
  blikPayLater: "PL",
  bancomatPay: "IT",
  jeniuspay: "ID",
  klarna: "SE",
  afterpay: "AU",
  oxxopay: "MX",
  boletobancario: "BR",
  paysafecard: "AT",
  scalapay: "IT",
  crypto: "US",
  dragonpay: "PH",
  fpx: "MY",
  indomaret: "ID",
  thailandBanks: "TH",
  alfamart: "ID",
  zip: "AU",
  latviaBanks: "LV",
  fiuu: "MY",
  lithuaniaBanks: "LT",
};
