/**
 * Generates one Storybook story file per LPM entry in LPM_REGISTRY.
 *
 * Why are there 50 individual files instead of one dynamic file?
 * Storybook's static CSF indexer requires `title` and `tags: ["autodocs"]`
 * to be **literal** values in the exported `default` object of each story
 * file. Values that are spread in from a factory function are invisible at
 * index time, so no story or Docs page would be registered. Each file
 * therefore owns its own `title` string (and `tags`), while all other meta
 * and story logic is delegated to `shared/lpm/storyFactory`.
 *
 * This script auto-generates those boilerplate files from LPM_REGISTRY so
 * they never need to be maintained manually. Run it after adding, renaming,
 * or removing an LPM from the registry:
 *
 *   npm run generate:lpm-stories  (from packages/react-paypal-js-storybook/v6)
 *
 * The generated files are committed to source control so Storybook can be
 * built without running this script first.
 */

import * as fs from "node:fs";
import * as path from "node:path";
// Import directly from the workspace source to avoid published-package subpath
// resolution issues when running outside of the Vite/Storybook build context.
import { LPM_REGISTRY } from "../../../react-paypal-js/src/v6/config/lpmRegistry";
import type { LPMName } from "../../../react-paypal-js/src/v6/config/lpmRegistry";

const STORIES_DIR = path.join(
  path.dirname(new URL(import.meta.url).pathname),
  "../src/stories/lpm",
);

/** Capitalizes the first character of a camelCase key → PascalCase prefix. */
function toPascal(key: string): string {
  return key.charAt(0).toUpperCase() + key.slice(1);
}

/** Derives the story file name from the LPM registry key. */
function toFileName(key: string): string {
  return `${toPascal(key)}OneTimePaymentButton.stories.tsx`;
}

/** Generates the content of a single LPM story file. */
function generateStoryContent(key: LPMName, displayName: string): string {
  const pascal = toPascal(key);
  return `// This file is auto-generated by scripts/generate-lpm-stories.ts
// Run \`npm run generate:lpm-stories\` to regenerate after registry changes.
import type { Meta } from "@storybook/react";
import { createLPMMetaExtras, createLPMStories, type LPMStoryArgs } from "../../shared/lpm/storyFactory";

const meta: Meta<LPMStoryArgs> = {
  title: "V6/LPM/${displayName}",
  tags: ["autodocs"],
  ...createLPMMetaExtras("${key}"),
};

export default meta;

const stories = createLPMStories("${key}");
export const Default = stories.Default;
`;
}

function main(): void {
  const lpmEntries = Object.entries(LPM_REGISTRY) as [
    LPMName,
    (typeof LPM_REGISTRY)[LPMName],
  ][];

  let created = 0;
  let updated = 0;
  let unchanged = 0;

  for (const [key, config] of lpmEntries) {
    const fileName = toFileName(key);
    const filePath = path.join(STORIES_DIR, fileName);
    const content = generateStoryContent(key, config.displayName);

    const existing = fs.existsSync(filePath)
      ? fs.readFileSync(filePath, "utf8")
      : null;

    if (existing === content) {
      unchanged++;
    } else if (existing === null) {
      fs.writeFileSync(filePath, content, "utf8");
      console.log(`  created  ${fileName}`);
      created++;
    } else {
      fs.writeFileSync(filePath, content, "utf8");
      console.log(`  updated  ${fileName}`);
      updated++;
    }
  }

  // Remove story files that no longer have a registry entry
  const expectedFiles = new Set(lpmEntries.map(([key]) => toFileName(key)));
  const existingFiles = fs
    .readdirSync(STORIES_DIR)
    .filter((f) => f.endsWith(".stories.tsx"));

  let removed = 0;
  for (const file of existingFiles) {
    if (!expectedFiles.has(file)) {
      fs.rmSync(path.join(STORIES_DIR, file));
      console.log(`  removed  ${file}`);
      removed++;
    }
  }

  console.log(
    `\nDone. ${created} created, ${updated} updated, ${removed} removed, ${unchanged} unchanged.`,
  );
}

main();
