#!/usr/bin/env node
/**
 * Generator for LPM Storybook stories.
 *
 * Reads LPM_REGISTRY from @paypal/react-paypal-js and regenerates
 * src/stories/buttons/LPMOneTimePaymentButton.stories.tsx
 *
 * Run this whenever a new LPM is added to LPM_REGISTRY:
 *   npm run generate:lpm-stories
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { LPM_REGISTRY } from "@paypal/react-paypal-js/sdk-v6";
import type { LPMName } from "@paypal/react-paypal-js/sdk-v6";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Country codes for testBuyerCountry
const LPM_COUNTRY_MAP: Record<string, string> = {
  ideal: "NL",
  bancontact: "BE",
  eps: "AT",
  blik: "PL",
  mybank: "IT",
  trustly: "SE",
  p24: "PL",
  multibanco: "PT",
  bizum: "ES",
  swish: "SE",
  klarna: "SE",
  twint: "CH",
  wechatpay: "CN",
  afterpay: "AU",
  oxxopay: "MX",
  boletobancario: "BR",
  verkkopankki: "FI",
  payu: "PL",
  paysafecard: "AT",
  mbway: "PT",
  satispay: "IT",
  wero: "DE",
  floa: "FR",
  scalapay: "IT",
  grabpay: "SG",
  pixInternational: "BR",
  sepa: "DE",
  crypto: "US",
  doku: "ID",
  dragonpay: "PH",
  estonia: "EE",
  fpx: "MY",
  gopay: "ID",
  alipay: "CN",
  indomaret: "ID",
  indonesiaBanks: "ID",
  kredivo: "ID",
  linkaja: "ID",
  ovo: "ID",
  paysera: "LT",
  skrill: "AT",
  thailandBanks: "TH",
  blikPayLater: "PL",
  alfamart: "ID",
  zip: "AU",
  bancomatPay: "IT",
  latviaBanks: "LV",
  fiuu: "MY",
  lithuaniaBanks: "LT",
  jeniuspay: "ID",
};

// Region groupings for organized story exports
const REGION_GROUPS: { region: string; lpms: string[] }[] = [
  {
    region: "Europe — Western",
    lpms: ["ideal", "bancontact", "sepa", "wero", "floa", "satispay", "scalapay", "mybank", "bancomatPay", "multibanco", "mbway"],
  },
  {
    region: "Europe — Nordic & Baltic",
    lpms: ["trustly", "swish", "klarna", "verkkopankki", "estonia", "paysera", "latviaBanks", "lithuaniaBanks"],
  },
  {
    region: "Europe — Central & Eastern",
    lpms: ["eps", "blik", "blikPayLater", "p24", "payu", "bizum", "twint", "paysafecard", "skrill"],
  },
  {
    region: "Asia — Southeast",
    lpms: ["grabpay", "fpx", "fiuu", "doku", "gopay", "indomaret", "indonesiaBanks", "kredivo", "linkaja", "ovo", "alfamart", "jeniuspay", "dragonpay", "thailandBanks"],
  },
  {
    region: "Asia — East",
    lpms: ["alipay", "wechatpay"],
  },
  {
    region: "Americas",
    lpms: ["pixInternational", "boletobancario", "oxxopay", "crypto"],
  },
  {
    region: "Oceania",
    lpms: ["afterpay", "zip"],
  },
];

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function generateNamedExports(lpmKeys: string[]): string {
  return REGION_GROUPS.map(({ region, lpms }) => {
    const validLpms = lpms.filter((lpm) => lpmKeys.includes(lpm));
    if (validLpms.length === 0) return null;

    const dashes = "─".repeat(Math.max(0, 72 - region.length));
    const exports = validLpms
      .map((lpm) => `export const ${capitalize(lpm)} = lpmArgs("${lpm}" as LPMName);`)
      .join("\n");

    return `// ─── ${region} ${dashes}\n\n${exports}`;
  })
    .filter(Boolean)
    .join("\n\n");
}

function generate(): string {
  const lpmKeys = Object.keys(LPM_REGISTRY);
  const lpmCount = lpmKeys.length;

  // Any LPMs not covered by a region group go to "Other"
  const coveredLpms = new Set(REGION_GROUPS.flatMap((g) => g.lpms));
  const uncoveredLpms = lpmKeys.filter((lpm) => !coveredLpms.has(lpm));

  const namedExports = generateNamedExports(lpmKeys);
  const uncoveredExports =
    uncoveredLpms.length > 0
      ? `\n\n// ─── Other ${"─".repeat(65)}\n\n${uncoveredLpms.map((lpm) => `export const ${capitalize(lpm)} = lpmArgs("${lpm}" as LPMName);`).join("\n")}`
      : "";

  return `// AUTO-GENERATED by scripts/generateLpmStories.ts
// Do not edit manually. Run \`npm run generate:lpm-stories\` to regenerate.
// Generated from LPM_REGISTRY: ${lpmCount} LPMs

import type { Meta, StoryObj } from "@storybook/react";

import {
  LPMOneTimePaymentButton,
  LPM_REGISTRY,
} from "@paypal/react-paypal-js/sdk-v6";
import type { LPMName } from "@paypal/react-paypal-js/sdk-v6";
import {
  createOrder,
  oneTimePaymentCallbacks,
  presentationModeArgType,
  disabledArgType,
} from "../../shared/utils";
import { V6DocPageStructure } from "../../components";
import {
  getLPMNamedButtonCode,
  getLPMGenericButtonCode,
  getLPMHookCode,
  LPM_COUNTRY_MAP,
} from "../../shared/lpmCode";
import { withLPMPayPalProvider } from "../../decorators";

const meta: Meta<typeof LPMOneTimePaymentButton> = {
  title: "V6/LPM/LPMOneTimePaymentButton",
  component: LPMOneTimePaymentButton,
  tags: ["autodocs"],
  decorators: [withLPMPayPalProvider],
  parameters: {
    skipPayPalProvider: true,
    controls: { expanded: true },
    docs: {
      description: {
        component: \`Generic Local Payment Method (LPM) button for one-time payments.

${lpmCount} LPMs share the same base class, options type, and session interface in the V6 SDK.

**Three ways to use LPMs:**
- **Named component** — \\\`import { IdealOneTimePaymentButton } from "@paypal/react-paypal-js/sdk-v6"\\\` (recommended)
- **Generic component** — \\\`<LPMOneTimePaymentButton lpm="ideal" />\\\` (for dynamic selection)
- **Named hook** — \\\`const { session, Button } = useIdealOneTimePaymentSession(...)\\\` (full control, access to payment fields)\`,
      },
      page: () => (
        <V6DocPageStructure
          code={getLPMNamedButtonCode("ideal")}
          codeTitle="Named Component (Recommended): IdealOneTimePaymentButton"
          additionalExamples={[
            {
              title: "Generic Component: LPMOneTimePaymentButton",
              code: getLPMGenericButtonCode("ideal"),
            },
            {
              title: "Hook with Payment Fields: useIdealOneTimePaymentSession",
              code: getLPMHookCode("ideal"),
            },
          ]}
        />
      ),
    },
  },
  argTypes: {
    lpm: {
      control: { type: "select" },
      options: Object.keys(LPM_REGISTRY) as LPMName[],
      description:
        "The Local Payment Method to render. Each LPM maps to a named component export (e.g. \`ideal\` → \`IdealOneTimePaymentButton\`).",
      table: { category: "Config" },
    },
    presentationMode: {
      ...presentationModeArgType,
      options: ["popup", "redirect"],
      description: "How the LPM checkout flow is presented (popup recommended)",
    },
    testBuyerCountry: {
      control: { type: "text" },
      description:
        "Two-letter country code for the test buyer (e.g. NL for iDEAL, BE for Bancontact, PL for BLIK).",
      table: { category: "Config" },
    },
    disabled: disabledArgType,
    createOrder: {
      description: "Function called on button click that creates an order and returns \`{ orderId }\`.",
      table: { category: "Events" },
    },
    onApprove: {
      description: "Called when the buyer approves the payment.",
      table: { category: "Events" },
    },
    onCancel: {
      description: "Called when the buyer cancels the payment.",
      table: { category: "Events" },
    },
    onError: {
      description: "Called when an error occurs during the payment flow.",
      table: { category: "Events" },
    },
  },
};

export default meta;

type Story = StoryObj<typeof LPMOneTimePaymentButton>;

function lpmArgs(lpm: LPMName): Story {
  return {
    name: LPM_REGISTRY[lpm].displayName,
    args: {
      lpm,
      presentationMode: "popup",
      testBuyerCountry: LPM_COUNTRY_MAP[lpm],
      createOrder,
      ...oneTimePaymentCallbacks,
    },
  };
}

// ─── Default (interactive LPM selector) ─────────────────────────────────────

export const Default: Story = {
  args: {
    lpm: "ideal",
    presentationMode: "popup",
    testBuyerCountry: "NL",
    createOrder,
    ...oneTimePaymentCallbacks,
  },
};

${namedExports}${uncoveredExports}
`;
}

const outputPath = path.join(
  __dirname,
  "../src/stories/buttons/LPMOneTimePaymentButton.stories.tsx",
);

fs.writeFileSync(outputPath, generate(), "utf8");

const lpmCount = Object.keys(LPM_REGISTRY).length;
console.log(`✓ Generated ${path.relative(process.cwd(), outputPath)}`);
console.log(`✓ ${lpmCount} LPMs from LPM_REGISTRY`);
console.log("  Run `npm run storybook` to see the stories.");
