// AUTO-GENERATED by scripts/generateLpmStories.ts
// To regenerate after adding a new LPM to the registry: npm run generate:lpm-stories

import type { Meta, StoryObj } from "@storybook/react";

import {
  LPMOneTimePaymentButton,
  LPM_REGISTRY,
} from "@paypal/react-paypal-js/sdk-v6";
import type { LPMName } from "@paypal/react-paypal-js/sdk-v6";
import {
  createOrder,
  createOrderForLpm,
  oneTimePaymentCallbacks,
  presentationModeArgType,
  disabledArgType,
} from "../../shared/utils";
import { V6DocPageStructure } from "../../components";
import {
  getLPMNamedButtonCode,
  getLPMGenericButtonCode,
  getLPMHookCode,
  LPM_COUNTRY_MAP,
} from "../../shared/lpmCode";
import { withLPMPayPalProvider } from "../../decorators";

const meta: Meta<typeof LPMOneTimePaymentButton> = {
  title: "V6/LPM/LPMOneTimePaymentButton",
  component: LPMOneTimePaymentButton,
  tags: ["autodocs"],
  decorators: [withLPMPayPalProvider],
  parameters: {
    skipPayPalProvider: true,
    controls: { expanded: true },
    docs: {
      description: {
        component: `Generic Local Payment Method (LPM) button for one-time payments.

48+ LPMs (iDEAL, Bancontact, BLIK, Klarna, and others) share the same base class, options type, and session interface in the V6 SDK. This component renders the appropriate branded button for any supported LPM.

**Three ways to use LPMs:**
- **Named component** — \`import { IdealOneTimePaymentButton } from "@paypal/react-paypal-js/sdk-v6"\` (recommended)
- **Generic component** — \`<LPMOneTimePaymentButton lpm="ideal" />\` (for dynamic selection)
- **Named hook + standalone button** — \`const { NameField, ...session } = useIdealOneTimePaymentSession(...)\` then \`<IdealPaymentButton paymentSession={session} />\` (full layout control — fields and button can live anywhere in your component tree)

It relies on the \`<PayPalProvider />\` parent component for SDK initialization.`,
      },
      page: () => (
        <V6DocPageStructure
          code={getLPMNamedButtonCode("ideal")}
          codeTitle="Named Component (Recommended): IdealOneTimePaymentButton"
          additionalExamples={[
            {
              title: "Generic Component: LPMOneTimePaymentButton",
              code: getLPMGenericButtonCode("ideal"),
            },
            {
              title: "Hook with Payment Fields: useIdealOneTimePaymentSession",
              code: getLPMHookCode("ideal"),
            },
          ]}
        />
      ),
    },
  },
  argTypes: {
    lpm: {
      control: { type: "select" },
      options: Object.keys(LPM_REGISTRY) as LPMName[],
      description:
        "The Local Payment Method to render. Each LPM maps to a named component export (e.g. `ideal` → `IdealOneTimePaymentButton`).",
      table: { category: "Config" },
    },
    presentationMode: {
      ...presentationModeArgType,
      options: ["popup", "redirect"],
      description: "How the LPM checkout flow is presented (popup recommended for most LPMs)",
    },
    testBuyerCountry: {
      control: { type: "text" },
      description:
        "Two-letter country code for the test buyer (e.g. NL for iDEAL, BE for Bancontact, PL for BLIK). Required for sandbox testing.",
      table: { category: "Config" },
    },
    disabled: disabledArgType,
    createOrder: {
      description:
        "Function called on button click that creates an order and returns `{ orderId }`.",
      table: { category: "Events" },
    },
    onApprove: {
      description: "Called when the buyer approves the payment.",
      table: { category: "Events" },
    },
    onCancel: {
      description: "Called when the buyer cancels the payment.",
      table: { category: "Events" },
    },
    onError: {
      description: "Called when an error occurs during the payment flow.",
      table: { category: "Events" },
    },
  },
};

export default meta;

type Story = StoryObj<typeof LPMOneTimePaymentButton>;

// Session fields required by specific LPMs at start() time (not hosted PayPal fields).
// billingAddress / taxInfo / expiryDate are merchant-collected — supply test values here.
const LPM_SESSION_FIELDS: Partial<Record<LPMName, Record<string, unknown>>> = {
  boletobancario: {
    billingAddress: {
      streetAddress: "Rua Exemplo, 123",
      city: "São Paulo",
      state: "SP",
      postalCode: "01310-100",
      countryCode: "BR",
    },
    taxInfo: { taxId: "123.456.789-09", taxIdType: "BR_CPF" },
  },
};

function lpmArgs(lpm: LPMName): Story {
  return {
    name: LPM_REGISTRY[lpm].displayName,
    args: {
      lpm,
      presentationMode: "popup",
      testBuyerCountry: LPM_COUNTRY_MAP[lpm],
      createOrder: () => createOrderForLpm(lpm),
      ...oneTimePaymentCallbacks,
      ...(LPM_SESSION_FIELDS[lpm] ?? {}),
    },
  };
}

// ─── Default (interactive LPM selector) ─────────────────────────────────────

export const Default: Story = {
  args: {
    lpm: "ideal",
    presentationMode: "popup",
    testBuyerCountry: "NL",
    createOrder: () => createOrderForLpm("ideal"),
    ...oneTimePaymentCallbacks,
  },
};

// ─── Europe — Western ────────────────────────────────────────────────────────

export const Ideal = lpmArgs("ideal");
export const Bancontact = lpmArgs("bancontact");
export const Sepa = lpmArgs("sepa");
export const Wero = lpmArgs("wero");
export const Floa = lpmArgs("floa");
export const Satispay = lpmArgs("satispay");
export const Scalapay = lpmArgs("scalapay");
export const Mybank = lpmArgs("mybank");
export const BancomatPay = lpmArgs("bancomatPay");
export const Multibanco = lpmArgs("multibanco");
export const Mbway = lpmArgs("mbway");

// ─── Europe — Nordic & Baltic ────────────────────────────────────────────────

export const Trustly = lpmArgs("trustly");
export const Swish = lpmArgs("swish");
export const Klarna = lpmArgs("klarna");
export const Verkkopankki = lpmArgs("verkkopankki");
export const Estonia = lpmArgs("estonia");
export const Paysera = lpmArgs("paysera");
export const LatviaBanks = lpmArgs("latviaBanks");
export const LithuaniaBanks = lpmArgs("lithuaniaBanks");

// ─── Europe — Central & Eastern ──────────────────────────────────────────────

export const Eps = lpmArgs("eps");
export const Blik = lpmArgs("blik");
export const BlikPayLater = lpmArgs("blikPayLater");
export const P24 = lpmArgs("p24");
export const Payu = lpmArgs("payu");
export const Bizum = lpmArgs("bizum");
export const Twint = lpmArgs("twint");
export const Paysafecard = lpmArgs("paysafecard");
export const Skrill = lpmArgs("skrill");

// ─── Asia — Southeast ────────────────────────────────────────────────────────

export const Grabpay = lpmArgs("grabpay");
export const Fpx = lpmArgs("fpx");
export const Fiuu = lpmArgs("fiuu");
export const Doku = lpmArgs("doku");
export const Gopay = lpmArgs("gopay");
export const Indomaret = lpmArgs("indomaret");
export const IndonesiaBanks = lpmArgs("indonesiaBanks");
export const Kredivo = lpmArgs("kredivo");
export const Linkaja = lpmArgs("linkaja");
export const Ovo = lpmArgs("ovo");
export const Alfamart = lpmArgs("alfamart");
export const Jeniuspay = lpmArgs("jeniuspay");
export const Dragonpay = lpmArgs("dragonpay");
export const ThailandBanks = lpmArgs("thailandBanks");

// ─── Asia — East ─────────────────────────────────────────────────────────────

export const Alipay = lpmArgs("alipay");
export const Wechatpay = lpmArgs("wechatpay");

// ─── Americas ────────────────────────────────────────────────────────────────

export const PixInternational = lpmArgs("pixInternational");
export const Boletobancario = lpmArgs("boletobancario");
export const Oxxopay = lpmArgs("oxxopay");
export const Crypto = lpmArgs("crypto");

// ─── Oceania ─────────────────────────────────────────────────────────────────

export const Afterpay = lpmArgs("afterpay");
export const Zip = lpmArgs("zip");
