// This file is auto-generated by scripts/generate-lpm-stories.ts
// Run `npm run generate:lpm-stories` to regenerate after registry changes.
import type { Meta } from "@storybook/react";
import { createLPMMetaExtras, createLPMStories, type LPMStoryArgs } from "../../shared/lpm/storyFactory";

const meta: Meta<LPMStoryArgs> = {
  title: "V6/LPM/Lithuania Banks",
  tags: ["autodocs"],
  ...createLPMMetaExtras("lithuaniaBanks"),
};

export default meta;

const stories = createLPMStories("lithuaniaBanks");
export const Default = stories.Default;
