// This file is auto-generated by scripts/generate-lpm-stories.cjs
// Run `npm run generate:lpm-stories` after changing LPM_REGISTRY.
import type { Meta } from "@storybook/react";
import {
  createLPMMetaExtras,
  createLPMStories,
  type LPMStoryArgs,
} from "../../shared/lpm/storyFactory";

const meta: Meta<LPMStoryArgs> = {
  title: "V6/Local Payment Methods/Paysafecard",
  ...createLPMMetaExtras("paysafecard"),
};

export default meta;

export const Default = createLPMStories("paysafecard").Default;
