import type { LPMComponents, LPMSessionMethodName } from "../types";

export type SessionFieldType = "phone" | "billingAddress" | "taxInfo" | "expiryDate" | "dateOfBirth" | "numberOfInstallments";

export interface LPMConfig {
  readonly component: LPMComponents;
  readonly buttonTag: string;
  readonly sessionMethod: LPMSessionMethodName;
  readonly displayName: string;
  readonly fields: readonly string[];
  readonly sessionFields: readonly SessionFieldType[];
  readonly testBuyerCountry: string;
}

export const LPM_REGISTRY = {
  ideal: {
    component: "ideal-payments",
    buttonTag: "ideal-button",
    sessionMethod: "createIdealOneTimePaymentSession",
    displayName: "iDEAL",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "NL",
  },
  bancontact: {
    component: "bancontact-payments",
    buttonTag: "bancontact-button",
    sessionMethod: "createBancontactOneTimePaymentSession",
    displayName: "Bancontact",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "BE",
  },
  eps: {
    component: "eps-payments",
    buttonTag: "eps-button",
    sessionMethod: "createEpsOneTimePaymentSession",
    displayName: "EPS",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "AT",
  },
  blik: {
    component: "blik-payments",
    buttonTag: "blik-button",
    sessionMethod: "createBlikOneTimePaymentSession",
    displayName: "BLIK",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PL",
  },
  mybank: {
    component: "mybank-payments",
    buttonTag: "mybank-button",
    sessionMethod: "createMyBankOneTimePaymentSession",
    displayName: "MyBank",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "IT",
  },
  trustly: {
    component: "trustly-payments",
    buttonTag: "trustly-button",
    sessionMethod: "createTrustlyOneTimePaymentSession",
    displayName: "Trustly",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "SE",
  },
  p24: {
    component: "p24-payments",
    buttonTag: "p24-button",
    sessionMethod: "createP24OneTimePaymentSession",
    displayName: "Przelewy24",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PL",
  },
  multibanco: {
    component: "multibanco-payments",
    buttonTag: "multibanco-button",
    sessionMethod: "createMultibancoOneTimePaymentSession",
    displayName: "Multibanco",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PT",
  },
  bizum: {
    component: "bizum-payments",
    buttonTag: "bizum-button",
    sessionMethod: "createBizumOneTimePaymentSession",
    displayName: "Bizum",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "ES",
  },
  swish: {
    component: "swish-payments",
    buttonTag: "swish-button",
    sessionMethod: "createSwishOneTimePaymentSession",
    displayName: "Swish",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "SE",
  },
  twint: {
    component: "twint-payments",
    buttonTag: "twint-button",
    sessionMethod: "createTwintOneTimePaymentSession",
    displayName: "TWINT",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CH",
  },
  wechatpay: {
    component: "wechatpay-payments",
    buttonTag: "wechatpay-button",
    sessionMethod: "createWechatpayOneTimePaymentSession",
    displayName: "WeChat Pay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CN",
  },
  verkkopankki: {
    component: "verkkopankki-payments",
    buttonTag: "verkkopankki-button",
    sessionMethod: "createVerkkopankkiOneTimePaymentSession",
    displayName: "Verkkopankki",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "FI",
  },
  payu: {
    component: "payu-payments",
    buttonTag: "payu-button",
    sessionMethod: "createPayuOneTimePaymentSession",
    displayName: "PayU",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PL",
  },
  mbway: {
    component: "mbway-payments",
    buttonTag: "mbway-button",
    sessionMethod: "createMbWayOneTimePaymentSession",
    displayName: "MB WAY",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "PT",
  },
  satispay: {
    component: "satispay-payments",
    buttonTag: "satispay-button",
    sessionMethod: "createSatispayOneTimePaymentSession",
    displayName: "Satispay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "IT",
  },
  wero: {
    component: "wero-payments",
    buttonTag: "wero-button",
    sessionMethod: "createWeroOneTimePaymentSession",
    displayName: "Wero",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "DE",
  },
  floa: {
    component: "floa-payments",
    buttonTag: "floa-button",
    sessionMethod: "createFloaOneTimePaymentSession",
    displayName: "FLOA",
    fields: ["name"],
    sessionFields: ["dateOfBirth", "numberOfInstallments"],
    testBuyerCountry: "FR",
  },
  grabpay: {
    component: "grabpay-payments",
    buttonTag: "grabpay-button",
    sessionMethod: "createGrabpayOneTimePaymentSession",
    displayName: "GrabPay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "SG",
  },
  pixInternational: {
    component: "pix-international-payments",
    buttonTag: "pix-international-button",
    sessionMethod: "createPixInternationalOneTimePaymentSession",
    displayName: "Pix",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress", "taxInfo"],
    testBuyerCountry: "BR",
  },
  sepa: {
    component: "sepa-payments",
    buttonTag: "sepa-button",
    sessionMethod: "createSepaOneTimePaymentSession",
    displayName: "SEPA",
    fields: [],
    sessionFields: [],
    testBuyerCountry: "DE",
  },
  doku: {
    component: "doku-payments",
    buttonTag: "doku-button",
    sessionMethod: "createDOKUOneTimePaymentSession",
    displayName: "DOKU",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  estonia: {
    component: "estoniabank-payments",
    buttonTag: "estoniabank-button",
    sessionMethod: "createEstoniaOneTimePaymentSession",
    displayName: "Estonia Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "EE",
  },
  gopay: {
    component: "gopay-payments",
    buttonTag: "gopay-button",
    sessionMethod: "createGopayOneTimePaymentSession",
    displayName: "GoPay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  alipay: {
    component: "alipay-payments",
    buttonTag: "alipay-button",
    sessionMethod: "createAlipayOneTimePaymentSession",
    displayName: "Alipay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CN",
  },
  indonesiaBanks: {
    component: "indonesiabanks-payments",
    buttonTag: "indonesiabanks-button",
    sessionMethod: "createIndonesiaBanksOneTimePaymentSession",
    displayName: "Indonesia Banks",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  kredivo: {
    component: "kredivo-payments",
    buttonTag: "kredivo-button",
    sessionMethod: "createKredivoOneTimePaymentSession",
    displayName: "Kredivo",
    fields: ["name", "email"],
    sessionFields: ["phone", "taxInfo"],
    testBuyerCountry: "ID",
  },
  linkaja: {
    component: "linkaja-payments",
    buttonTag: "linkaja-button",
    sessionMethod: "createLinkajaOneTimePaymentSession",
    displayName: "LinkAja",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  ovo: {
    component: "ovo-payments",
    buttonTag: "ovo-button",
    sessionMethod: "createOvoOneTimePaymentSession",
    displayName: "OVO",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
  paysera: {
    component: "paysera-payments",
    buttonTag: "paysera-button",
    sessionMethod: "createPayseraOneTimePaymentSession",
    displayName: "Paysera",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "LT",
  },
  skrill: {
    component: "skrill-payments",
    buttonTag: "skrill-button",
    sessionMethod: "createSkrillOneTimePaymentSession",
    displayName: "Skrill",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "DE",
  },
  blikPayLater: {
    component: "blikpaylater-payments",
    buttonTag: "blikpaylater-button",
    sessionMethod: "createBlikPayLaterOneTimePaymentSession",
    displayName: "BLIK Pay Later",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PL",
  },
  bancomatPay: {
    component: "bancomatpay-payments",
    buttonTag: "bancomatpay-button",
    sessionMethod: "createBancomatPayOneTimePaymentSession",
    displayName: "Bancomat Pay",
    fields: ["name"],
    sessionFields: ["phone", "taxInfo"],
    testBuyerCountry: "IT",
  },
  jeniuspay: {
    component: "jeniuspay-payments",
    buttonTag: "jeniuspay-button",
    sessionMethod: "createJeniuspayOneTimePaymentSession",
    displayName: "Jeniuspay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
  },
} as const satisfies Record<string, LPMConfig>;

export type LPMName = keyof typeof LPM_REGISTRY;
