import type { LPMComponents, LPMSessionMethodName } from "../types";

export type SessionFieldType =
  | "phone"
  | "billingAddress"
  | "taxInfo"
  | "expiryDate"
  | "dateOfBirth"
  | "numberOfInstallments";

export type LPMFieldType = "name" | "email" | "tax_id" | "tax_id_type";

export interface LPMConfig {
  readonly component: LPMComponents;
  readonly buttonTag: string;
  readonly sessionMethod: LPMSessionMethodName;
  readonly displayName: string;
  readonly fields: readonly LPMFieldType[];
  readonly sessionFields: readonly SessionFieldType[];
  readonly testBuyerCountry: string;
  /** Currency the LPM's test buyer country transacts in, used to create orders and check eligibility. */
  readonly currencyCode: string;
}

export const LPM_REGISTRY = {
  ideal: {
    component: "ideal-payments",
    buttonTag: "ideal-button",
    sessionMethod: "createIdealOneTimePaymentSession",
    displayName: "iDEAL",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "NL",
    currencyCode: "EUR",
  },
  bancontact: {
    component: "bancontact-payments",
    buttonTag: "bancontact-button",
    sessionMethod: "createBancontactOneTimePaymentSession",
    displayName: "Bancontact",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "BE",
    currencyCode: "EUR",
  },
  eps: {
    component: "eps-payments",
    buttonTag: "eps-button",
    sessionMethod: "createEpsOneTimePaymentSession",
    displayName: "EPS",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "AT",
    currencyCode: "EUR",
  },
  blik: {
    component: "blik-payments",
    buttonTag: "blik-button",
    sessionMethod: "createBlikOneTimePaymentSession",
    displayName: "BLIK",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PL",
    currencyCode: "PLN",
  },
  mybank: {
    component: "mybank-payments",
    buttonTag: "mybank-button",
    sessionMethod: "createMyBankOneTimePaymentSession",
    displayName: "MyBank",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "IT",
    currencyCode: "EUR",
  },
  trustly: {
    component: "trustly-payments",
    buttonTag: "trustly-button",
    sessionMethod: "createTrustlyOneTimePaymentSession",
    displayName: "Trustly",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "SE",
    currencyCode: "SEK",
  },
  p24: {
    component: "p24-payments",
    buttonTag: "p24-button",
    sessionMethod: "createP24OneTimePaymentSession",
    displayName: "Przelewy24",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PL",
    currencyCode: "PLN",
  },
  multibanco: {
    component: "multibanco-payments",
    buttonTag: "multibanco-button",
    sessionMethod: "createMultibancoOneTimePaymentSession",
    displayName: "Multibanco",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PT",
    currencyCode: "EUR",
  },
  bizum: {
    component: "bizum-payments",
    buttonTag: "bizum-button",
    sessionMethod: "createBizumOneTimePaymentSession",
    displayName: "Bizum",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "ES",
    currencyCode: "EUR",
  },
  swish: {
    component: "swish-payments",
    buttonTag: "swish-button",
    sessionMethod: "createSwishOneTimePaymentSession",
    displayName: "Swish",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "SE",
    currencyCode: "SEK",
  },
  twint: {
    component: "twint-payments",
    buttonTag: "twint-button",
    sessionMethod: "createTwintOneTimePaymentSession",
    displayName: "TWINT",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CH",
    currencyCode: "CHF",
  },
  wechatpay: {
    component: "wechatpay-payments",
    buttonTag: "wechatpay-button",
    sessionMethod: "createWechatpayOneTimePaymentSession",
    displayName: "WeChat Pay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CN",
    currencyCode: "CNY",
  },
  verkkopankki: {
    component: "verkkopankki-payments",
    buttonTag: "verkkopankki-button",
    sessionMethod: "createVerkkopankkiOneTimePaymentSession",
    displayName: "Verkkopankki",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "FI",
    currencyCode: "EUR",
  },
  payu: {
    component: "payu-payments",
    buttonTag: "payu-button",
    sessionMethod: "createPayuOneTimePaymentSession",
    displayName: "PayU",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PL",
    currencyCode: "PLN",
  },
  mbway: {
    component: "mbway-payments",
    buttonTag: "mbway-button",
    sessionMethod: "createMbWayOneTimePaymentSession",
    displayName: "MB WAY",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "PT",
    currencyCode: "EUR",
  },
  satispay: {
    component: "satispay-payments",
    buttonTag: "satispay-button",
    sessionMethod: "createSatispayOneTimePaymentSession",
    displayName: "Satispay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "IT",
    currencyCode: "EUR",
  },
  wero: {
    component: "wero-payments",
    buttonTag: "wero-button",
    sessionMethod: "createWeroOneTimePaymentSession",
    displayName: "Wero",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "DE",
    currencyCode: "EUR",
  },
  floa: {
    component: "floa-payments",
    buttonTag: "floa-button",
    sessionMethod: "createFloaOneTimePaymentSession",
    displayName: "FLOA",
    fields: ["name"],
    sessionFields: ["dateOfBirth", "numberOfInstallments"],
    testBuyerCountry: "FR",
    currencyCode: "EUR",
  },
  grabpay: {
    component: "grabpay-payments",
    buttonTag: "grabpay-button",
    sessionMethod: "createGrabpayOneTimePaymentSession",
    displayName: "GrabPay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "SG",
    currencyCode: "SGD",
  },
  pixInternational: {
    component: "pix-international-payments",
    buttonTag: "pix-international-button",
    sessionMethod: "createPixInternationalOneTimePaymentSession",
    displayName: "Pix",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress", "taxInfo"],
    testBuyerCountry: "BR",
    currencyCode: "BRL",
  },
  sepa: {
    component: "sepa-payments",
    buttonTag: "sepa-button",
    sessionMethod: "createSepaOneTimePaymentSession",
    displayName: "SEPA",
    fields: [],
    sessionFields: [],
    testBuyerCountry: "DE",
    currencyCode: "EUR",
  },
  doku: {
    component: "doku-payments",
    buttonTag: "doku-button",
    sessionMethod: "createDOKUOneTimePaymentSession",
    displayName: "DOKU",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  estonia: {
    component: "estoniabank-payments",
    buttonTag: "estonia-button",
    sessionMethod: "createEstoniaOneTimePaymentSession",
    displayName: "Estonia Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "EE",
    currencyCode: "EUR",
  },
  gopay: {
    component: "gopay-payments",
    buttonTag: "gopay-button",
    sessionMethod: "createGopayOneTimePaymentSession",
    displayName: "GoPay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  alipay: {
    component: "alipay-payments",
    buttonTag: "alipay-button",
    sessionMethod: "createAlipayOneTimePaymentSession",
    displayName: "Alipay",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "CN",
    currencyCode: "CNY",
  },
  indonesiaBanks: {
    component: "indonesiabanks-payments",
    buttonTag: "indonesiabanks-button",
    sessionMethod: "createIndonesiaBanksOneTimePaymentSession",
    displayName: "Indonesia Banks",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  kredivo: {
    component: "kredivo-payments",
    buttonTag: "kredivo-button",
    sessionMethod: "createKredivoOneTimePaymentSession",
    displayName: "Kredivo",
    fields: ["name", "email"],
    sessionFields: ["phone", "taxInfo"],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  linkaja: {
    component: "linkaja-payments",
    buttonTag: "linkaja-button",
    sessionMethod: "createLinkajaOneTimePaymentSession",
    displayName: "LinkAja",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  ovo: {
    component: "ovo-payments",
    buttonTag: "ovo-button",
    sessionMethod: "createOvoOneTimePaymentSession",
    displayName: "OVO",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  paysera: {
    component: "paysera-payments",
    buttonTag: "paysera-button",
    sessionMethod: "createPayseraOneTimePaymentSession",
    displayName: "Paysera",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "LT",
    currencyCode: "EUR",
  },
  skrill: {
    component: "skrill-payments",
    buttonTag: "skrill-button",
    sessionMethod: "createSkrillOneTimePaymentSession",
    displayName: "Skrill",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "DE",
    currencyCode: "EUR",
  },
  blikPayLater: {
    component: "blikpaylater-payments",
    buttonTag: "blikpaylater-button",
    sessionMethod: "createBlikPayLaterOneTimePaymentSession",
    displayName: "BLIK Pay Later",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "PL",
    currencyCode: "PLN",
  },
  bancomatPay: {
    component: "bancomatpay-payments",
    buttonTag: "bancomatpay-button",
    sessionMethod: "createBancomatPayOneTimePaymentSession",
    displayName: "Bancomat Pay",
    fields: ["name"],
    sessionFields: ["phone", "taxInfo"],
    testBuyerCountry: "IT",
    currencyCode: "EUR",
  },
  jeniuspay: {
    component: "jeniuspay-payments",
    buttonTag: "jeniuspay-button",
    sessionMethod: "createJeniuspayOneTimePaymentSession",
    displayName: "Jeniuspay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  klarna: {
    component: "klarna-payments",
    buttonTag: "klarna-button",
    sessionMethod: "createKlarnaOneTimePaymentSession",
    displayName: "Klarna",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "SE",
    currencyCode: "SEK",
  },
  afterpay: {
    component: "afterpay-payments",
    buttonTag: "afterpay-button",
    sessionMethod: "createAfterpayOneTimePaymentSession",
    displayName: "Afterpay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "AU",
    currencyCode: "AUD",
  },
  oxxopay: {
    component: "oxxopay-payments",
    buttonTag: "oxxopay-button",
    sessionMethod: "createOxxopayOneTimePaymentSession",
    displayName: "OXXO",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "MX",
    currencyCode: "MXN",
  },
  boletobancario: {
    component: "boletobancario-payments",
    buttonTag: "boletobancario-button",
    sessionMethod: "createBoletobancarioOneTimePaymentSession",
    displayName: "Boleto Bancário",
    fields: ["name", "email"],
    sessionFields: ["taxInfo"],
    testBuyerCountry: "BR",
    currencyCode: "BRL",
  },
  paysafecard: {
    component: "paysafecard-payments",
    buttonTag: "paysafecard-button",
    sessionMethod: "createPaysafecardOneTimePaymentSession",
    displayName: "Paysafecard",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "AT",
    currencyCode: "EUR",
  },
  scalapay: {
    component: "scalapay-payments",
    buttonTag: "scalapay-button",
    sessionMethod: "createScalapayOneTimePaymentSession",
    displayName: "Scalapay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "IT",
    currencyCode: "EUR",
  },
  crypto: {
    component: "crypto-payments",
    buttonTag: "crypto-button",
    sessionMethod: "createCryptoOneTimePaymentSession",
    displayName: "Crypto",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "US",
    currencyCode: "USD",
  },
  dragonpay: {
    component: "dragonpay-payments",
    buttonTag: "dragonpay-button",
    sessionMethod: "createDragonpayOneTimePaymentSession",
    displayName: "Dragonpay",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "PH",
    currencyCode: "PHP",
  },
  fpx: {
    component: "fpx-payments",
    buttonTag: "fpx-button",
    sessionMethod: "createFpxOneTimePaymentSession",
    displayName: "FPX",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "MY",
    currencyCode: "MYR",
  },
  indomaret: {
    component: "indomaret-payments",
    buttonTag: "indomaret-button",
    sessionMethod: "createIndomaretOneTimePaymentSession",
    displayName: "Indomaret",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  thailandBanks: {
    component: "thailand-banks-payments",
    buttonTag: "thailandbanks-button",
    sessionMethod: "createThailandBanksOneTimePaymentSession",
    displayName: "Thailand Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "TH",
    currencyCode: "THB",
  },
  alfamart: {
    component: "alfamart-payments",
    buttonTag: "alfamart-button",
    sessionMethod: "createAlfamartOneTimePaymentSession",
    displayName: "Alfamart",
    fields: ["name", "email"],
    sessionFields: [],
    testBuyerCountry: "ID",
    currencyCode: "IDR",
  },
  zip: {
    component: "zip-payments",
    buttonTag: "zip-button",
    sessionMethod: "createZipOneTimePaymentSession",
    displayName: "Zip",
    fields: ["name"],
    sessionFields: ["phone", "billingAddress"],
    testBuyerCountry: "AU",
    currencyCode: "AUD",
  },
  latviaBanks: {
    component: "latviabanks-payments",
    buttonTag: "latviabanks-button",
    sessionMethod: "createLatviaBanksOneTimePaymentSession",
    displayName: "Latvia Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "LV",
    currencyCode: "EUR",
  },
  fiuu: {
    // FIUU's SDK component is "fiuu-cash-payments" but the registered
    // custom-element button tag is "fiuu-button" (not "fiuu-cash-button"),
    // so buttonTag does NOT follow the standard component→tag derivation.
    component: "fiuu-cash-payments",
    buttonTag: "fiuu-button",
    sessionMethod: "createFIUUOneTimePaymentSession",
    displayName: "FIUU",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "MY",
    currencyCode: "MYR",
  },
  lithuaniaBanks: {
    component: "lithuaniabanks-payments",
    buttonTag: "lithuaniabanks-button",
    sessionMethod: "createLithuaniaBanksOneTimePaymentSession",
    displayName: "Lithuania Banks",
    fields: ["name"],
    sessionFields: [],
    testBuyerCountry: "LT",
    currencyCode: "EUR",
  },
} as const satisfies Record<string, LPMConfig>;

export type LPMName = keyof typeof LPM_REGISTRY;
