import type { LPMComponents, LPMSessionMethodName } from "../types";

export type SessionFieldType = "phone" | "billingAddress" | "taxInfo" | "expiryDate";

export interface LPMConfig {
  readonly component: LPMComponents;
  readonly buttonTag: string;
  readonly sessionMethod: LPMSessionMethodName;
  readonly displayName: string;
  readonly fields: readonly string[];
  readonly sessionFields: readonly SessionFieldType[];
}

export const LPM_REGISTRY = {
  ideal: {
    component: "ideal-payments",
    buttonTag: "ideal-button",
    sessionMethod: "createIdealOneTimePaymentSession",
    displayName: "iDEAL",
    fields: ["name"],
    sessionFields: [],
  },
  bancontact: {
    component: "bancontact-payments",
    buttonTag: "bancontact-button",
    sessionMethod: "createBancontactOneTimePaymentSession",
    displayName: "Bancontact",
    fields: ["name"],
    sessionFields: [],
  },
  eps: {
    component: "eps-payments",
    buttonTag: "eps-button",
    sessionMethod: "createEpsOneTimePaymentSession",
    displayName: "EPS",
    fields: ["name"],
    sessionFields: [],
  },
  blik: {
    component: "blik-payments",
    buttonTag: "blik-button",
    sessionMethod: "createBlikOneTimePaymentSession",
    displayName: "BLIK",
    fields: ["name", "email"],
    sessionFields: [],
  },
  mybank: {
    component: "mybank-payments",
    buttonTag: "mybank-button",
    sessionMethod: "createMyBankOneTimePaymentSession",
    displayName: "MyBank",
    fields: ["name"],
    sessionFields: [],
  },
  trustly: {
    component: "trustly-payments",
    buttonTag: "trustly-button",
    sessionMethod: "createTrustlyOneTimePaymentSession",
    displayName: "Trustly",
    fields: ["name", "email"],
    sessionFields: [],
  },
  p24: {
    component: "p24-payments",
    buttonTag: "p24-button",
    sessionMethod: "createP24OneTimePaymentSession",
    displayName: "Przelewy24",
    fields: ["name", "email"],
    sessionFields: [],
  },
  multibanco: {
    component: "multibanco-payments",
    buttonTag: "multibanco-button",
    sessionMethod: "createMultibancoOneTimePaymentSession",
    displayName: "Multibanco",
    fields: ["name"],
    sessionFields: [],
  },
  bizum: {
    component: "bizum-payments",
    buttonTag: "bizum-button",
    sessionMethod: "createBizumOneTimePaymentSession",
    displayName: "Bizum",
    fields: ["name"],
    sessionFields: [],
  },
  swish: {
    component: "swish-payments",
    buttonTag: "swish-button",
    sessionMethod: "createSwishOneTimePaymentSession",
    displayName: "Swish",
    fields: ["name"],
    sessionFields: [],
  },
  klarna: {
    component: "klarna-payments",
    buttonTag: "klarna-button",
    sessionMethod: "createKlarnaOneTimePaymentSession",
    displayName: "Klarna",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress"],
  },
  twint: {
    component: "twint-payments",
    buttonTag: "twint-button",
    sessionMethod: "createTwintOneTimePaymentSession",
    displayName: "TWINT",
    fields: ["name"],
    sessionFields: [],
  },
  wechatpay: {
    component: "wechatpay-payments",
    buttonTag: "wechatpay-button",
    sessionMethod: "createWechatpayOneTimePaymentSession",
    displayName: "WeChat Pay",
    fields: ["name"],
    sessionFields: [],
  },
  afterpay: {
    component: "afterpay-payments",
    buttonTag: "afterpay-button",
    sessionMethod: "createAfterpayOneTimePaymentSession",
    displayName: "Afterpay",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress"],
  },
  oxxopay: {
    component: "oxxopay-payments",
    buttonTag: "oxxopay-button",
    sessionMethod: "createOxxopayOneTimePaymentSession",
    displayName: "OXXO",
    fields: ["name", "email"],
    sessionFields: [],
  },
  boletobancario: {
    component: "boletobancario-payments",
    buttonTag: "boletobancario-button",
    sessionMethod: "createBoletobancarioOneTimePaymentSession",
    displayName: "Boleto Bancário",
    fields: ["name", "email"],
    sessionFields: ["billingAddress", "taxInfo", "expiryDate"],
  },
  verkkopankki: {
    component: "verkkopankki-payments",
    buttonTag: "verkkopankki-button",
    sessionMethod: "createVerkkopankkiOneTimePaymentSession",
    displayName: "Verkkopankki",
    fields: ["name", "email"],
    sessionFields: [],
  },
  payu: {
    component: "payu-payments",
    buttonTag: "payu-button",
    sessionMethod: "createPayuOneTimePaymentSession",
    displayName: "PayU",
    fields: ["name"],
    sessionFields: [],
  },
  paysafecard: {
    component: "paysafecard-payments",
    buttonTag: "paysafecard-button",
    sessionMethod: "createPaysafecardOneTimePaymentSession",
    displayName: "Paysafecard",
    fields: ["name"],
    sessionFields: [],
  },
  mbway: {
    component: "mbway-payments",
    buttonTag: "mbway-button",
    sessionMethod: "createMbWayOneTimePaymentSession",
    displayName: "MB WAY",
    fields: ["name", "email"],
    sessionFields: ["phone"],
  },
  satispay: {
    component: "satispay-payments",
    buttonTag: "satispay-button",
    sessionMethod: "createSatispayOneTimePaymentSession",
    displayName: "Satispay",
    fields: ["name"],
    sessionFields: [],
  },
  wero: {
    component: "wero-payments",
    buttonTag: "wero-button",
    sessionMethod: "createWeroOneTimePaymentSession",
    displayName: "Wero",
    fields: ["name"],
    sessionFields: [],
  },
  floa: {
    component: "floa-payments",
    buttonTag: "floa-button",
    sessionMethod: "createFloaOneTimePaymentSession",
    displayName: "FLOA",
    fields: ["name"],
    sessionFields: [],
  },
  scalapay: {
    component: "scalapay-payments",
    buttonTag: "scalapay-button",
    sessionMethod: "createScalapayOneTimePaymentSession",
    displayName: "Scalapay",
    fields: ["name", "email"],
    sessionFields: ["phone", "taxInfo"],
  },
  grabpay: {
    component: "grabpay-payments",
    buttonTag: "grabpay-button",
    sessionMethod: "createGrabpayOneTimePaymentSession",
    displayName: "GrabPay",
    fields: ["name"],
    sessionFields: [],
  },
  pixInternational: {
    component: "pix-international-payments",
    buttonTag: "pix-international-button",
    sessionMethod: "createPixInternationalOneTimePaymentSession",
    displayName: "Pix",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress"],
  },
  sepa: {
    component: "sepa-payments",
    buttonTag: "sepa-button",
    sessionMethod: "createSepaOneTimePaymentSession",
    displayName: "SEPA",
    fields: [],
    sessionFields: [],
  },
  crypto: {
    component: "crypto-payments",
    buttonTag: "crypto-button",
    sessionMethod: "createCryptoOneTimePaymentSession",
    displayName: "Crypto",
    fields: ["name"],
    sessionFields: [],
  },
  doku: {
    component: "doku-payments",
    buttonTag: "doku-button",
    sessionMethod: "createDOKUOneTimePaymentSession",
    displayName: "DOKU",
    fields: ["name", "email"],
    sessionFields: ["phone"],
  },
  dragonpay: {
    component: "dragonpay-payments",
    buttonTag: "dragonpay-button",
    sessionMethod: "createDragonpayOneTimePaymentSession",
    displayName: "Dragonpay",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress"],
  },
  estonia: {
    component: "estoniabank-payments",
    buttonTag: "estonia-button",
    sessionMethod: "createEstoniaOneTimePaymentSession",
    displayName: "Estonia Banks",
    fields: ["name"],
    sessionFields: [],
  },
  fpx: {
    component: "fpx-payments",
    buttonTag: "fpx-button",
    sessionMethod: "createFpxOneTimePaymentSession",
    displayName: "FPX",
    fields: ["name"],
    sessionFields: [],
  },
  gopay: {
    component: "gopay-payments",
    buttonTag: "gopay-button",
    sessionMethod: "createGopayOneTimePaymentSession",
    displayName: "GoPay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
  },
  alipay: {
    component: "alipay-payments",
    buttonTag: "alipay-button",
    sessionMethod: "createAlipayOneTimePaymentSession",
    displayName: "Alipay",
    fields: ["name"],
    sessionFields: [],
  },
  indomaret: {
    component: "indomaret-payments",
    buttonTag: "indomaret-button",
    sessionMethod: "createIndomaretOneTimePaymentSession",
    displayName: "Indomaret",
    fields: ["name", "email"],
    sessionFields: ["phone"],
  },
  indonesiaBanks: {
    component: "indonesiabanks-payments",
    buttonTag: "indonesiabanks-button",
    sessionMethod: "createIndonesiaBanksOneTimePaymentSession",
    displayName: "Indonesia Banks",
    fields: ["name", "email"],
    sessionFields: ["phone"],
  },
  kredivo: {
    component: "kredivo-payments",
    buttonTag: "kredivo-button",
    sessionMethod: "createKredivoOneTimePaymentSession",
    displayName: "Kredivo",
    fields: ["name", "email"],
    sessionFields: ["phone", "taxInfo"],
  },
  linkaja: {
    component: "linkaja-payments",
    buttonTag: "linkaja-button",
    sessionMethod: "createLinkajaOneTimePaymentSession",
    displayName: "LinkAja",
    fields: ["name", "email"],
    sessionFields: ["phone"],
  },
  ovo: {
    component: "ovo-payments",
    buttonTag: "ovo-button",
    sessionMethod: "createOvoOneTimePaymentSession",
    displayName: "OVO",
    fields: ["name", "email"],
    sessionFields: ["phone"],
  },
  paysera: {
    component: "paysera-payments",
    buttonTag: "paysera-button",
    sessionMethod: "createPayseraOneTimePaymentSession",
    displayName: "Paysera",
    fields: ["name", "email"],
    sessionFields: [],
  },
  skrill: {
    component: "skrill-payments",
    buttonTag: "skrill-button",
    sessionMethod: "createSkrillOneTimePaymentSession",
    displayName: "Skrill",
    fields: ["name"],
    sessionFields: [],
  },
  thailandBanks: {
    component: "thailandbanks-payments",
    buttonTag: "thailandbanks-button",
    sessionMethod: "createThailandBanksOneTimePaymentSession",
    displayName: "Thailand Banks",
    fields: ["name"],
    sessionFields: [],
  },
  blikPayLater: {
    component: "blikpaylater-payments",
    buttonTag: "blikpaylater-button",
    sessionMethod: "createBlikPayLaterOneTimePaymentSession",
    displayName: "BLIK Pay Later",
    fields: ["name"],
    sessionFields: [],
  },
  alfamart: {
    component: "alfamart-payments",
    buttonTag: "alfamart-button",
    sessionMethod: "createAlfamartOneTimePaymentSession",
    displayName: "Alfamart",
    fields: ["name", "email"],
    sessionFields: ["phone", "billingAddress"],
  },
  zip: {
    component: "zip-payments",
    buttonTag: "zip-button",
    sessionMethod: "createZipOneTimePaymentSession",
    displayName: "Zip",
    fields: ["name"],
    sessionFields: ["phone", "billingAddress"],
  },
  bancomatPay: {
    component: "bancomatpay-payments",
    buttonTag: "bancomatpay-button",
    sessionMethod: "createBancomatPayOneTimePaymentSession",
    displayName: "Bancomat Pay",
    fields: ["name"],
    sessionFields: ["phone", "taxInfo"],
  },
  latviaBanks: {
    component: "latviabanks-payments",
    buttonTag: "latviabanks-button",
    sessionMethod: "createLatviaBanksOneTimePaymentSession",
    displayName: "Latvia Banks",
    fields: ["name"],
    sessionFields: [],
  },
  fiuu: {
    component: "fiuu-cash-payments",
    buttonTag: "fiuu-button",
    sessionMethod: "createFIUUOneTimePaymentSession",
    displayName: "FIUU",
    fields: ["name"],
    sessionFields: [],
  },
  lithuaniaBanks: {
    component: "lithuaniabanks-payments",
    buttonTag: "lithuaniabanks-button",
    sessionMethod: "createLithuaniaBanksOneTimePaymentSession",
    displayName: "Lithuania Banks",
    fields: ["name"],
    sessionFields: [],
  },
  jeniuspay: {
    component: "jeniuspay-payments",
    buttonTag: "jeniuspay-button",
    sessionMethod: "createJeniuspayOneTimePaymentSession",
    displayName: "Jeniuspay",
    fields: ["name", "email"],
    sessionFields: ["phone"],
  },
} as const satisfies Record<string, LPMConfig>;

export type LPMName = keyof typeof LPM_REGISTRY;
